name: docs 

# 1. Define when the script should run
on:
  push:
    branches:
      - main  # Runs every time you push to main

# 2. Grant permissions required for GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          #cache: 'pip'   # if using this we need a **/requirements.txt or **/pyproject.toml file

      - name: Install dependencies
        run: pip install mkdocs-material pymdown-extensions mkdocs-enumerate-headings-plugin

      - name: Build Documentation
        run: |
          mkdocs build
          #cp CNAME site/CNAME  # injects the domain file into the build folder

      # 3. Tell GitHub where the "cooked" website files are
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/ 

      # 4. Hand the files over to the live server
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
